# Generated by Django 3.0.7 on 2020-06-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='creater',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieApp.Movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rator',
            field=models.CharField(max_length=100),
        ),
    ]
