# Generated by Django 3.0.7 on 2020-06-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_auto_20200616_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='creater',
            new_name='creator',
        ),
    ]
