# Generated by Django 3.0.7 on 2020-06-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
    ]
